env_settings:
  num_areas: 8
behaviors:
  MazeBBT:
    trainer_type: ppo               # SAC also works; PPO is default & stable
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 4096
      buffer_size: 409600
      beta: 5e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 256
      num_layers: 2
      memory:   # LSTM
        sequence_length: 128         # gives the agent short-term memory
        memory_size: 256
      normalize: true
      # vis_encode_type: fully_connected  # for processing grid observation
      vis_encode_type: simple

      # vibe-coded in: does it exist?
      # sensor_settings:
      #   - name: GridSensor  # name set in Unity editor
      #     encoding_type: simple  # Options: simple, resnet, match3, nature_cnn (for visual)
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20e6                 # ~2-4 h on a modern GPU with 16 envs
    time_horizon: 128

environment_parameters:
  maze_seed:
    sampler_type: uniform
    sampler_parameters: {min_value: 0, max_value: 2_000_000}

  difficulty:               # later used for curriculum
    sampler_type: uniform
    sampler_parameters: {min_value: 0.1, max_value: 0.1}
