env_settings:
  num_areas: 8
behaviors:
  EndToEndMazeSolver:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 4096
      buffer_size: 409600
      beta: 5e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 256
      num_layers: 2
      memory:   # LSTM
        sequence_length: 128         # gives the agent short-term memory
        memory_size: 256
      normalize: true
      vis_encode_type: simple # for processing grid observation
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50e6
    time_horizon: 128
  HierarchicalMazeSolver:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 4096
      buffer_size: 204800
      beta: 5e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 256
      num_layers: 2
      normalize: true
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50e6
    time_horizon: 128
    summary_freq: 10000

environment_parameters:
  maze_seed:
    sampler_type: uniform
    sampler_parameters: {min_value: 0, max_value: 2_000_000}

  difficulty:               # later could be used for curriculum
    sampler_type: uniform
    sampler_parameters: {min_value: 0.1, max_value: 0.1}
